// retrogradeMeanings — STATIC, pre-written plain-language copy for the Retrograde
// (Vakri) Tracker. Written ONCE, reused forever. NEVER generated by AI at runtime.
// One calm paragraph per planet; framed constructively (a time to review/refine, not
// doom). Rahu/Ketu are excluded from the tracker (they are always retrograde/vakri).

export type RetroPlanet = 'Mercury' | 'Venus' | 'Mars' | 'Jupiter' | 'Saturn';

// The 5 planets the tracker follows, in the order we display upcoming periods.
export const RETRO_PLANETS: RetroPlanet[] = ['Mercury', 'Venus', 'Mars', 'Jupiter', 'Saturn'];

// Display name (English + Sanskrit) shown as "Mercury (Budh)".
export const PLANET_LABEL: Record<RetroPlanet, string> = {
  Mercury: 'Mercury (Budh)',
  Venus: 'Venus (Shukra)',
  Mars: 'Mars (Mangal)',
  Jupiter: 'Jupiter (Guru)',
  Saturn: 'Saturn (Shani)',
};

// One theme word per planet, for the compact card sub-line.
export const PLANET_THEME: Record<RetroPlanet, string> = {
  Mercury: 'communication · travel · contracts',
  Venus: 'relationships · finances',
  Mars: 'energy · initiative',
  Jupiter: 'growth · plans',
  Saturn: 'structures · patience',
};

// The full, calm explanation shown when a planet is retrograde (or in its detail row).
export const RETRO_MEANING: Record<RetroPlanet, string> = {
  Mercury:
    'When Budh turns vakri, matters of communication, travel and paperwork ask for a ' +
    'second look. It is a natural time to review rather than rush — re-read messages, ' +
    'confirm plans and travel details, and hold off on signing important contracts until ' +
    'you are sure. Old conversations and people from the past may resurface. Handled ' +
    'patiently, it is simply a period to refine and double-check, not to fear.',
  Venus:
    'A vakri Shukra draws attention back to relationships, values and money. Feelings you ' +
    'had set aside may return for reflection, and it becomes a thoughtful time to reconsider ' +
    'what — and who — you truly value. Rather than beginning something entirely new in love ' +
    'or finances, it favours revisiting, reconciling and appreciating what you already have.',
  Mars:
    'When Mangal is vakri, energy and drive turn inward. Projects may seem to slow or need ' +
    'rethinking, and it is wiser to channel effort into planning and steady work than to force ' +
    'confrontation or hasty action. Patience with yourself and others pays off; the momentum ' +
    'returns once Mangal resumes direct motion.',
  Jupiter:
    'A vakri Guru invites you to revisit your growth, beliefs and long-term plans. It is a ' +
    'reflective, philosophical period — a chance to deepen learning, review commitments and ' +
    'realign with what genuinely gives your life meaning, rather than expanding outward all at ' +
    'once. Inner growth quietly prepares the ground for later expansion.',
  Saturn:
    'When Shani turns vakri, long-term structures, duties and discipline come up for review. ' +
    'It is a patient, consolidating time to strengthen foundations, tidy up responsibilities ' +
    'and finish what was left incomplete. Progress may feel measured rather than fast — steady ' +
    'effort and honesty with yourself are rewarded well beyond this period.',
};

// ── Hindi (Devanagari) variants ──────────────────────────────────────────────
export const PLANET_LABEL_HI: Record<RetroPlanet, string> = {
  Mercury: 'बुध', Venus: 'शुक्र', Mars: 'मंगल', Jupiter: 'गुरु', Saturn: 'शनि',
};

export const PLANET_THEME_HI: Record<RetroPlanet, string> = {
  Mercury: 'संवाद · यात्रा · अनुबंध',
  Venus: 'संबंध · वित्त',
  Mars: 'ऊर्जा · पहल',
  Jupiter: 'विकास · योजनाएं',
  Saturn: 'संरचना · धैर्य',
};

export const RETRO_MEANING_HI: Record<RetroPlanet, string> = {
  Mercury:
    'जब बुध वक्री होते हैं, संवाद, यात्रा और कागज़ी काम दोबारा देखने की माँग करते हैं। यह जल्दबाज़ी ' +
    'के बजाय समीक्षा का स्वाभाविक समय है — संदेश दोबारा पढ़ें, योजनाओं और यात्रा विवरणों की पुष्टि करें, ' +
    'और तब तक महत्वपूर्ण अनुबंधों पर हस्ताक्षर टालें जब तक आप निश्चित न हों। पुरानी बातचीत और अतीत के लोग ' +
    'फिर सामने आ सकते हैं। धैर्य से संभालें तो यह बस परिष्कृत और दोबारा जाँचने की अवधि है, डरने की नहीं।',
  Venus:
    'वक्री शुक्र ध्यान को संबंधों, मूल्यों और धन की ओर वापस लाते हैं। जो भावनाएं आपने एक ओर रख दी थीं वे ' +
    'चिंतन के लिए लौट सकती हैं, और यह विचार करने का समय बन जाता है कि आप वास्तव में किसे और किसको महत्व ' +
    'देते हैं। प्रेम या वित्त में कुछ बिल्कुल नया शुरू करने के बजाय, यह जो पहले से है उसे दोबारा देखने, ' +
    'सुलझाने और सराहने के अनुकूल है।',
  Mars:
    'जब मंगल वक्री होते हैं, ऊर्जा और प्रेरणा अंतर्मुखी हो जाती है। कार्य धीमे लग सकते हैं या पुनर्विचार ' +
    'माँग सकते हैं, और टकराव या जल्दबाज़ी के बजाय प्रयास को योजना और स्थिर कार्य में लगाना बुद्धिमानी है। ' +
    'स्वयं और दूसरों के साथ धैर्य फल देता है; मंगल के सीधे होते ही गति लौट आती है।',
  Jupiter:
    'वक्री गुरु आपको अपने विकास, विश्वासों और दीर्घकालिक योजनाओं पर दोबारा विचार करने का न्योता देते हैं। ' +
    'यह चिंतनशील, दार्शनिक अवधि है — सीखने को गहरा करने, प्रतिबद्धताओं की समीक्षा करने और जो सचमुच आपके ' +
    'जीवन को अर्थ देता है उसके साथ पुनः तालमेल बिठाने का अवसर। भीतरी विकास चुपचाप बाद के विस्तार की भूमि ' +
    'तैयार करता है।',
  Saturn:
    'जब शनि वक्री होते हैं, दीर्घकालिक संरचनाएं, कर्तव्य और अनुशासन समीक्षा के लिए सामने आते हैं। यह ' +
    'धैर्यपूर्ण, सुदृढ़ करने का समय है — नींव मज़बूत करने, ज़िम्मेदारियों को व्यवस्थित करने और अधूरे कार्य ' +
    'पूरे करने का। प्रगति तेज़ के बजाय नपी-तुली लग सकती है — स्थिर प्रयास और स्वयं के प्रति ईमानदारी इस ' +
    'अवधि से कहीं आगे तक पुरस्कृत होती है।',
};
