// retrogradeMeanings — STATIC, pre-written plain-language copy for the Retrograde
// (Vakri) Tracker. Written ONCE, reused forever. NEVER generated by AI at runtime.
// One calm paragraph per planet; framed constructively (a time to review/refine, not
// doom). Rahu/Ketu are excluded from the tracker (they are always retrograde/vakri).

export type RetroPlanet = 'Mercury' | 'Venus' | 'Mars' | 'Jupiter' | 'Saturn';

// The 5 planets the tracker follows, in the order we display upcoming periods.
export const RETRO_PLANETS: RetroPlanet[] = ['Mercury', 'Venus', 'Mars', 'Jupiter', 'Saturn'];

// Display name (English + Sanskrit) shown as "Mercury (Budh)".
export const PLANET_LABEL: Record<RetroPlanet, string> = {
  Mercury: 'Mercury (Budh)',
  Venus: 'Venus (Shukra)',
  Mars: 'Mars (Mangal)',
  Jupiter: 'Jupiter (Guru)',
  Saturn: 'Saturn (Shani)',
};

// One theme word per planet, for the compact card sub-line.
export const PLANET_THEME: Record<RetroPlanet, string> = {
  Mercury: 'communication · travel · contracts',
  Venus: 'relationships · finances',
  Mars: 'energy · initiative',
  Jupiter: 'growth · plans',
  Saturn: 'structures · patience',
};

// The full, calm explanation shown when a planet is retrograde (or in its detail row).
export const RETRO_MEANING: Record<RetroPlanet, string> = {
  Mercury:
    'When Budh turns vakri, matters of communication, travel and paperwork ask for a ' +
    'second look. It is a natural time to review rather than rush — re-read messages, ' +
    'confirm plans and travel details, and hold off on signing important contracts until ' +
    'you are sure. Old conversations and people from the past may resurface. Handled ' +
    'patiently, it is simply a period to refine and double-check, not to fear.',
  Venus:
    'A vakri Shukra draws attention back to relationships, values and money. Feelings you ' +
    'had set aside may return for reflection, and it becomes a thoughtful time to reconsider ' +
    'what — and who — you truly value. Rather than beginning something entirely new in love ' +
    'or finances, it favours revisiting, reconciling and appreciating what you already have.',
  Mars:
    'When Mangal is vakri, energy and drive turn inward. Projects may seem to slow or need ' +
    'rethinking, and it is wiser to channel effort into planning and steady work than to force ' +
    'confrontation or hasty action. Patience with yourself and others pays off; the momentum ' +
    'returns once Mangal resumes direct motion.',
  Jupiter:
    'A vakri Guru invites you to revisit your growth, beliefs and long-term plans. It is a ' +
    'reflective, philosophical period — a chance to deepen learning, review commitments and ' +
    'realign with what genuinely gives your life meaning, rather than expanding outward all at ' +
    'once. Inner growth quietly prepares the ground for later expansion.',
  Saturn:
    'When Shani turns vakri, long-term structures, duties and discipline come up for review. ' +
    'It is a patient, consolidating time to strengthen foundations, tidy up responsibilities ' +
    'and finish what was left incomplete. Progress may feel measured rather than fast — steady ' +
    'effort and honesty with yourself are rewarded well beyond this period.',
};
