-- Free Home features: Panchang (daily almanac) + Numerology
-- Run in Supabase SQL Editor AFTER 001–009. Re-runnable.
--
-- Both features are COMPUTED with code/formulas and cached — NEVER generated by
-- the AI/LLM. No Claude/OpenAI calls are involved in either.
--
-- 1) PANCHANG — generic daily almanac, SAME for everyone in the same city on the
--    same day (not personalised). Computed ONCE per (place, date) by the `panchang`
--    Edge Function (pure astronomy, service-role writer) and SHARED: every user in
--    that city reads the same cached row. `place_key` is the lat/lng rounded to 1
--    decimal (~11 km grid) so a whole city collapses to one cache row.
--
-- 2) NUMEROLOGY — derived from a profile's name + DOB in plain client code and
--    cached on the profile row (jsonb) so it isn't recomputed on every view. The
--    interpretation TEXT is a fixed pre-written library bundled in the app; only the
--    computed numbers + refs are stored here.

-- ─── PANCHANG CACHE ───────────────────────────────────────────────────────────
create table if not exists public.panchang_cache (
  id          uuid primary key default gen_random_uuid(),
  place_key   text not null,           -- 'lat.d,lng.d' rounded to 1 decimal (city bucket)
  place_label text,                    -- human city/birth-place label for display
  date_key    text not null,           -- IST day 'YYYY-MM-DD' (Asia/Kolkata)
  data        jsonb not null,          -- full computed panchang (tithi, nakshatra, timings…)
  created_at  timestamptz not null default now()
);

-- One cached almanac per place+day (also the insert conflict target).
create unique index if not exists uq_panchang_place_date
  on public.panchang_cache(place_key, date_key);

alter table public.panchang_cache enable row level security;

-- Shared, non-sensitive content: any signed-in user may read; only the service
-- role (Edge Function) writes. No client insert/update/delete.
drop policy if exists "panchang: read for authenticated" on public.panchang_cache;
create policy "panchang: read for authenticated" on public.panchang_cache
  for select to authenticated using (true);

-- ─── NUMEROLOGY (cached on the profile) ───────────────────────────────────────
-- { life_path:{number,is_master}, expression:{number,is_master}, computed_at }
alter table public.profiles
  add column if not exists numerology jsonb;
