-- Free Home tool: Shubh Muhurat Finder
-- Run in Supabase SQL Editor AFTER 001–010. Re-runnable.
--
-- Auspicious dates/windows for a chosen activity, COMPUTED from Panchang + a fixed
-- rule set (config/muhuratRules.ts) — NEVER generated by AI. The `muhurat` Edge
-- Function computes each day's Panchang in pure code, matches the activity's rules,
-- and caches the whole result here per (activity, city, date-range) for the day.
--
--   place_key : lat/lng rounded to 1 decimal (~11 km city grid) — same as panchang_cache
--   range_key : 'START_END' IST ISO dates ('YYYY-MM-DD_YYYY-MM-DD')

create table if not exists public.muhurat_cache (
  id          uuid primary key default gen_random_uuid(),
  activity    text not null,
  place_key   text not null,
  range_key   text not null,
  data        jsonb not null,      -- { results:[...], count, place, ... }
  created_at  timestamptz not null default now()
);

-- One cached result per activity+place+range (also the insert conflict target).
create unique index if not exists uq_muhurat_activity_place_range
  on public.muhurat_cache(activity, place_key, range_key);

alter table public.muhurat_cache enable row level security;

-- Shared, non-sensitive content: any signed-in user may read; only the service
-- role (Edge Function) writes.
drop policy if exists "muhurat: read for authenticated" on public.muhurat_cache;
create policy "muhurat: read for authenticated" on public.muhurat_cache
  for select to authenticated using (true);
